# Generated by Django 5.2.8 on 2025-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binge_watch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='binge_risk_score',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_score',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
